### ISSUE TITLE
Batman: Arkham Asylum (non-steam) demo reports 'graphics card doesn't meet the minimum spec' (detect video adapter memory via WMI)

### ISSUE THREAD

**Issue by deri82** [wine-compholio/wine-staging#144]
I think several games are impacted by this bug.

https://bugs.winehq.org/show_bug.cgi?id=32834

**Comment by deri82** [comment]
I have misunderstood the bug to another. This might have been fixed already for some.

**Comment by slackner** [comment]
Afaik this bug isn't fixed yet, @DarkPlayer was working on it. Could you open a new bug in our new bugtracker and assign it to him, so that this issue doesn't get lost?

**Comment by deri82** [comment]
done
