### ISSUE TITLE
Mirror's Edge couldn't make use of nvcuda

### ISSUE THREAD

**Issue by felixonmars** [wine-compholio/wine-staging#264]
Looks like this is the cause:
```
fixme:nvapi:unimplemented_stub function 0xceee8e9f is unimplemented!
```

Full output with +nvcuda:
```
err:wineconsole:WCUSER_SetFont wrong font
err:wineconsole:WCUSER_SetFont wrong font
err:setupapi:do_file_copyW Unsupported style(s) 0x144
err:setupapi:do_file_copyW Unsupported style(s) 0x144
err:setupapi:do_file_copyW Unsupported style(s) 0x144
err:setupapi:do_file_copyW Unsupported style(s) 0x144
err:setupapi:do_file_copyW Unsupported style(s) 0x144
err:setupapi:do_file_copyW Unsupported style(s) 0x144
err:setupapi:do_file_copyW Unsupported style(s) 0x144
err:setupapi:do_file_copyW Unsupported style(s) 0x144
err:setupapi:do_file_copyW Unsupported style(s) 0x144
err:setupapi:do_file_copyW Unsupported style(s) 0x144
err:setupapi:do_file_copyW Unsupported style(s) 0x144
err:setupapi:do_file_copyW Unsupported style(s) 0x144
err:setupapi:do_file_copyW Unsupported style(s) 0x144
err:setupapi:do_file_copyW Unsupported style(s) 0x144
err:setupapi:do_file_copyW Unsupported style(s) 0x144
err:setupapi:do_file_copyW Unsupported style(s) 0x144
err:setupapi:do_file_copyW Unsupported style(s) 0x144
err:setupapi:do_file_copyW Unsupported style(s) 0x144
err:setupapi:do_file_copyW Unsupported style(s) 0x144
err:setupapi:do_file_copyW Unsupported style(s) 0x144
err:setupapi:do_file_copyW Unsupported style(s) 0x144
err:setupapi:do_file_copyW Unsupported style(s) 0x144
err:setupapi:do_file_copyW Unsupported style(s) 0x144
err:setupapi:do_file_copyW Unsupported style(s) 0x144
err:setupapi:do_file_copyW Unsupported style(s) 0x144
err:setupapi:do_file_copyW Unsupported style(s) 0x144
err:setupapi:do_file_copyW Unsupported style(s) 0x144
err:setupapi:do_file_copyW Unsupported style(s) 0x144
err:setupapi:do_file_copyW Unsupported style(s) 0x144
err:setupapi:do_file_copyW Unsupported style(s) 0x144
err:setupapi:do_file_copyW Unsupported style(s) 0x144
err:setupapi:do_file_copyW Unsupported style(s) 0x144
fixme:setupapi:extract_cabinet_file awful hack: extracting cabinet "C:\\windows\\system32\\DirectX\\DXe242.tmp\\APR2007_xinput_x86.cab"
fixme:ver:GetCurrentPackageId (0x33f7bc (nil)): stub
fixme:module:load_dll Loader redirect from L"wined3d.dll" to L"wined3d-csmt.dll"
fixme:advapi:EventRegister {47a9201e-73b0-42ce-9821-7e134361bc6f}, 0x30221e0, 0x30c22c8, 0x30c22c0
fixme:advapi:EventRegister {58a9201e-73b0-42ce-9821-7e134361bc70}, 0x30221e0, 0x30c2300, 0x30c22f8
fixme:advapi:EventRegister {3fa9201e-73b0-43fe-9821-7e145359bc6f}, 0x30221e0, 0x30c2290, 0x30c2288
fixme:advapi:EventRegister {1432afee-73b0-42ce-9821-7e134361b433}, 0x30221e0, 0x30c2338, 0x30c2330
fixme:advapi:EventRegister {4372afee-73b0-42ce-9821-7e134361b519}, 0x30221e0, 0x30c2370, 0x30c2368
fixme:imm:ImmGetOpenStatus (0x1c2290): semi-stub
fixme:ver:GetCurrentPackageId (0x267f1bc (nil)): stub
fixme:winediag:wined3d_dll_init Experimental wined3d CSMT feature is currently enabled.
fixme:advapi:EventRegister {47a9201e-73b0-42ce-9821-7e134361bc6f}, 0x3f006fe0, 0x3f03fce8, 0x3f03fce0
fixme:advapi:EventRegister {58a9201e-73b0-42ce-9821-7e134361bc70}, 0x3f006fe0, 0x3f03fd20, 0x3f03fd18
fixme:advapi:EventRegister {3fa9201e-73b0-43fe-9821-7e145359bc6f}, 0x3f006fe0, 0x3f03fcb0, 0x3f03fca8
fixme:advapi:EventRegister {1432afee-73b0-42ce-9821-7e134361b433}, 0x3f006fe0, 0x3f03fd58, 0x3f03fd50
fixme:advapi:EventRegister {4372afee-73b0-42ce-9821-7e134361b519}, 0x3f006fe0, 0x3f03fd90, 0x3f03fd88
fixme:advapi:EventUnregister deadbeef: stub
fixme:advapi:EventUnregister deadbeef: stub
fixme:advapi:EventUnregister deadbeef: stub
fixme:advapi:EventUnregister deadbeef: stub
fixme:advapi:EventUnregister deadbeef: stub
fixme:gameux:GameExplorerImpl_VerifyAccess (0x460e310, L"Z:\\home\\felix\\Games\\Steam\\SteamApps\\common\\mirrors edge\\Binaries\\MirrorsEdge.exe", 0x267f2f8)
fixme:nvapi:unimplemented_stub function 0xe5ac921f is unimplemented!
trace:nvcuda:DllMain (0xf43c0000, 1, (nil))
trace:nvcuda:wine_cuInit (0)
fixme:nvapi:unimplemented_stub function 0xceee8e9f is unimplemented!
trace:nvcuda:wine_cuDeviceGetAttribute (0x267f218, 537396226, 0)
trace:nvcuda:DllMain (0xf43c0000, 0, (nil))
fixme:msvcrt:__clean_type_info_names_internal (0x89d4ed0) stub
trace:nvcuda:DllMain (0xf43c0000, 1, (nil))
trace:nvcuda:wine_cuInit (0)
fixme:nvapi:unimplemented_stub function 0xceee8e9f is unimplemented!
trace:nvcuda:wine_cuDeviceGetAttribute (0x267aee0, 537396226, 0)
trace:nvcuda:DllMain (0xf43c0000, 0, (nil))
fixme:msvcrt:__clean_type_info_names_internal (0x89d4ed0) stub
trace:nvcuda:DllMain (0xf43c0000, 1, (nil))
trace:nvcuda:wine_cuInit (0)
fixme:nvapi:unimplemented_stub function 0xceee8e9f is unimplemented!
trace:nvcuda:wine_cuDeviceGetAttribute (0x267f1e8, 537396226, 0)
trace:nvcuda:DllMain (0xf43c0000, 0, (nil))
fixme:msvcrt:__clean_type_info_names_internal (0x89d4ed0) stub
fixme:system:SystemParametersInfoW Unimplemented action: 59 (SPI_SETSTICKYKEYS)
fixme:system:SystemParametersInfoW Unimplemented action: 53 (SPI_SETTOGGLEKEYS)
fixme:system:SystemParametersInfoW Unimplemented action: 51 (SPI_SETFILTERKEYS)
fixme:d3d:debug_d3dformat Unrecognized 0x34324644 (as fourcc: DF24) WINED3DFORMAT!
fixme:d3d:wined3d_get_format Can't find format unrecognized (0x34324644) in the format lookup table
fixme:advapi:EventRegister {47a9201e-73b0-42ce-9821-7e134361bc6f}, 0x3f006fe0, 0x3f03fce8, 0x3f03fce0
fixme:advapi:EventRegister {58a9201e-73b0-42ce-9821-7e134361bc70}, 0x3f006fe0, 0x3f03fd20, 0x3f03fd18
fixme:advapi:EventRegister {3fa9201e-73b0-43fe-9821-7e145359bc6f}, 0x3f006fe0, 0x3f03fcb0, 0x3f03fca8
fixme:advapi:EventRegister {1432afee-73b0-42ce-9821-7e134361b433}, 0x3f006fe0, 0x3f03fd58, 0x3f03fd50
fixme:advapi:EventRegister {4372afee-73b0-42ce-9821-7e134361b519}, 0x3f006fe0, 0x3f03fd90, 0x3f03fd88
fixme:process:SetProcessShutdownParameters (000003ff, 00000000): partial stub.
fixme:ver:GetCurrentPackageId (0x33e18c (nil)): stub
fixme:ver:GetCurrentPackageId (0x31f000 (nil)): stub
fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_HANDLE_INFORMATION
fixme:imm:ImmGetOpenStatus (0x1b4a88): semi-stub
fixme:ver:GetCurrentPackageId (0x33e7e4 (nil)): stub
fixme:imm:ImmReleaseContext (0x5015c, (nil)): stub
fixme:winhttp:get_system_proxy_autoconfig_url no support on this platform
fixme:imm:ImmReleaseContext (0x5015c, 0x1bffe9e8): stub
fixme:system:SystemParametersInfoW Unknown action: 116
err:d3d_surface:wined3d_surface_load_location Don't know how to handle location 0x100.
fixme:msvcrt:__clean_type_info_names_internal (0x2b40168) stub
fixme:msvcrt:__clean_type_info_names_internal (0x3f6018) stub
fixme:msvcrt:__clean_type_info_names_internal (0x2aec158) stub
fixme:msvcrt:__clean_type_info_names_internal (0x29eb168) stub
fixme:msvcrt:__clean_type_info_names_internal (0x3e6018) stub
fixme:msvcrt:__clean_type_info_names_internal (0x26f7250) stub
fixme:msvcrt:__clean_type_info_names_internal (0x3ae528) stub
fixme:msvcrt:__clean_type_info_names_internal (0x2833648) stub
fixme:msvcrt:__clean_type_info_names_internal (0x2780d10) stub
fixme:msvcrt:__clean_type_info_names_internal (0x102db700) stub
fixme:msvcrt:__clean_type_info_names_internal (0x375570) stub
fixme:advapi:EventUnregister deadbeef: stub
fixme:advapi:EventUnregister deadbeef: stub
fixme:advapi:EventUnregister deadbeef: stub
fixme:advapi:EventUnregister deadbeef: stub
fixme:advapi:EventUnregister deadbeef: stub
fixme:advapi:EventUnregister deadbeef: stub
fixme:advapi:EventUnregister deadbeef: stub
fixme:advapi:EventUnregister deadbeef: stub
fixme:advapi:EventUnregister deadbeef: stub
fixme:advapi:EventUnregister deadbeef: stub
```

**Comment by slackner** [comment]
Marking as bug, it most likely needs an implementation for both unimplemented functions

```
fixme:nvapi:unimplemented_stub function 0xe5ac921f is unimplemented!
fixme:nvapi:unimplemented_stub function 0xceee8e9f is unimplemented!
```

@DarkPlayer: Do you have time to work on this? If yes feel free to assign it.

**Comment by DarkPlayer** [comment]
I think about implementing the existing functions through [NVML](https://developer.nvidia.com/nvidia-management-library-nvml) first instead of using stubs. Otherwise we need to rebase all existing patches again when we add a real implementation.

**Comment by slackner** [comment]
i don't think adding a real implementation is necessary - at least we're not aware of any programs which need it. Moreover just returning dummy information for one graphic card should be work for most of our users.

Why not wait with a real implementation until it is required later?

**Comment by DarkPlayer** [comment]
@slackner This way we are never going to support multi gpu systems and moreover we also return completely wrong device names at the moment. Since NVML is like CUDA part of the driver I don't see a reason why we shouldn't add a real implementation. I will still keep the stub code as fallback in case the necessary library can not be loaded.

**Comment by DarkPlayer** [comment]
According to https://bugs.winehq.org/show_bug.cgi?id=25723#c11 it should work after you remove the PhysX files from Mirror Edge (You need to have the PhysX driver installed). Does this solve the problem for you @felixonmars?

**Comment by felixonmars** [comment]
Confirmed, removing the files solves this for me. Would the original DLLs be supported somehow or this will be the workaround I have to keep?

**Comment by DarkPlayer** [comment]
I am currently writing a patch which might solve the problem for the original dlls, so you can try it out.

**Comment by DarkPlayer** [comment]
Can you try the following two patches with the original dlls? They should implement the missing functions:

https://dl.dropboxusercontent.com/u/61413222/0001-nvapi-Add-stub-for-NvAPI_EnumPhysicalGPUs.patch
https://dl.dropboxusercontent.com/u/61413222/0002-nvapi-Add-stubs-for-NvAPI_GPU_GetFullName.patch

**Comment by DarkPlayer** [comment]
I have updated the first patch. The function definition didn't contain `CDECL` causing a crash on 64 bit.

**Comment by DarkPlayer** [comment]
I pushed the patches into the repository, so you can directly test the current git version.

**Comment by felixonmars** [comment]
So it still doesn't work. No more nvapi fixmes but the nvcuda routine wasn't used during gameplay.

**Comment by felixonmars** [comment]
And this is part of the output when I removed the shipped PhysX DLLs, as a comparison:

```
fixme:module:load_dll Loader redirect from L"wined3d.dll" to L"wined3d-csmt.dll"
fixme:advapi:EventRegister {47a9201e-73b0-42ce-9821-7e134361bc6f}, 0x30221e0, 0x30c22c8, 0x30c22c0
fixme:advapi:EventRegister {58a9201e-73b0-42ce-9821-7e134361bc70}, 0x30221e0, 0x30c2300, 0x30c22f8
fixme:advapi:EventRegister {3fa9201e-73b0-43fe-9821-7e145359bc6f}, 0x30221e0, 0x30c2290, 0x30c2288
fixme:advapi:EventRegister {1432afee-73b0-42ce-9821-7e134361b433}, 0x30221e0, 0x30c2338, 0x30c2330
fixme:advapi:EventRegister {4372afee-73b0-42ce-9821-7e134361b519}, 0x30221e0, 0x30c2370, 0x30c2368
fixme:imm:ImmGetOpenStatus (0x1c2a70): semi-stub
fixme:ver:GetCurrentPackageId (0x267f1bc (nil)): stub
fixme:winediag:wined3d_dll_init Experimental wined3d CSMT feature is currently enabled.
fixme:advapi:EventRegister {47a9201e-73b0-42ce-9821-7e134361bc6f}, 0x3f006fe0, 0x3f03fce8, 0x3f03fce0
fixme:advapi:EventRegister {58a9201e-73b0-42ce-9821-7e134361bc70}, 0x3f006fe0, 0x3f03fd20, 0x3f03fd18
fixme:advapi:EventRegister {3fa9201e-73b0-43fe-9821-7e145359bc6f}, 0x3f006fe0, 0x3f03fcb0, 0x3f03fca8
fixme:advapi:EventRegister {1432afee-73b0-42ce-9821-7e134361b433}, 0x3f006fe0, 0x3f03fd58, 0x3f03fd50
fixme:advapi:EventRegister {4372afee-73b0-42ce-9821-7e134361b519}, 0x3f006fe0, 0x3f03fd90, 0x3f03fd88
fixme:advapi:EventUnregister deadbeef: stub
fixme:advapi:EventUnregister deadbeef: stub
fixme:advapi:EventUnregister deadbeef: stub
fixme:advapi:EventUnregister deadbeef: stub
fixme:advapi:EventUnregister deadbeef: stub
fixme:gameux:GameExplorerImpl_VerifyAccess (0x460f9a0, L"Z:\\home\\felix\\Games\\Steam\\SteamApps\\common\\mirrors edge\\Binaries\\MirrorsEdge.exe", 0x267f2f8)
trace:nvcuda:DllMain (0xf4390000, 1, (nil))
trace:nvcuda:wine_cuInit (0)
trace:nvcuda:wine_cuInit (0)
trace:nvcuda:wine_cuDeviceGetCount (0x267b460)
trace:nvcuda:wine_cuDeviceGetAttribute (0x267b428, 537396226, 0)
trace:nvcuda:wine_cuDriverGetVersion (0x87802e8)
trace:nvcuda:wine_cuInit (0)
trace:nvcuda:wine_cuGetExportTable (0x87802d8, 0x789b04c)
trace:nvcuda:wine_cuGetExportTable (0x87802dc, 0x789b05c)
trace:nvcuda:wine_cuDeviceGetCount (0x8781ff8)
trace:nvcuda:wine_cuDeviceGet (0x267f7c0, 0)
trace:nvcuda:Unknown1_func1_relay (0x8782000, (nil))
trace:nvcuda:wine_cuDeviceGetName (0x8782008, 256, 0)
trace:nvcuda:wine_cuDeviceTotalMem_v2 (0x8782108, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x8782140, 75, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x8782144, 76, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x8782150, 15, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x8782224, 40, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x8782154, 16, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x8782158, 17, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x878215c, 18, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x8782160, 19, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x8782168, 21, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x878216c, 77, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x8782170, 69, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x8782174, 22, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x8782178, 23, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x878217c, 73, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x8782180, 74, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x8782184, 70, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x8782188, 71, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x878218c, 72, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x8782190, 45, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x8782194, 46, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x8782198, 24, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x878219c, 25, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x87821a0, 26, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x87821a4, 47, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x87821a8, 48, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x87821ac, 49, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x87821b0, 52, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x87821b4, 42, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x87821b8, 43, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x87821bc, 27, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x87821c0, 28, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x87821c4, 29, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x87821c8, 53, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x87821cc, 54, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x87821d0, 55, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x87821d4, 56, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x87821d8, 57, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x87821dc, 58, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x87821e0, 59, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x87821e4, 60, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x87821e8, 61, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x87821ec, 62, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x87821f0, 63, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x87821f4, 64, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x87821f8, 65, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x87821fc, 66, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x8782200, 67, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x8782204, 68, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x878220c, 31, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x8782210, 32, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x8782214, 33, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x8782218, 34, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x878221c, 50, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x8782220, 35, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x8782228, 41, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x878222c, 36, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x8782230, 37, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x8782234, 38, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x8782238, 39, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x267f7b8, 30, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x267f7b4, 51, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x267f7b0, 8, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x267f7ac, 81, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x8782110, 12, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x878224c, 82, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x8782114, 10, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x267f7a8, 11, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x878211c, 1, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x8782120, 2, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x8782124, 3, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x8782128, 4, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x878212c, 5, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x8782130, 6, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x8782134, 7, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x267f7a4, 9, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x8782138, 13, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x267f7a0, 14, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x878223c, 78, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x8782240, 79, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x8782244, 80, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x8782250, 83, 0)
trace:nvcuda:Unknown2_func1_relay (0x87802e4, 0x267f7d8)
trace:nvcuda:wine_cuGetExportTable (0x87802e0, 0x789b06c)
trace:nvcuda:wine_cuGetExportTable (0x267f7b4, 0x789c248)
trace:nvcuda:wine_cuDeviceGetAttribute (0x8782158, 17, 0)
trace:nvcuda:wine_cuDeviceGetAttribute (0x8782164, 20, 0)
trace:nvcuda:DllMain (0xf4390000, 2, (nil))
trace:nvcuda:cuda_process_tls_callbacks (2)
trace:nvcuda:wine_cuInit (0)
trace:nvcuda:wine_cuDeviceGetCount (0x8e0e9b0)
trace:nvcuda:wine_cuDeviceGet (0x8e0e9b4, 0)
trace:nvcuda:wine_cuGetExportTable (0x8e0e9b8, 0x844e30c)
trace:nvcuda:Unknown5_func0_relay (0x4f08724, 0x14, (nil))
trace:nvcuda:ContextStorage_Get (0x8e0e918, (nil), 0x878b608)
trace:nvcuda:wine_cuCtxGetCurrent (0x8e0e900)
trace:nvcuda:wine_cuCtxGetApiVersion (0xf40ade70, 0x8e0e8fc)
trace:nvcuda:ContextStorage_Get (0x8e0e900, (nil), 0x878b608)
trace:nvcuda:wine_cuCtxGetCurrent (0x8e0e8f8)
trace:nvcuda:wine_cuCtxGetDevice (0x8e0e8fc)
trace:nvcuda:ContextStorage_Set ((nil), 0x878b608, 0x878b628, 0x787dd30)
trace:nvcuda:Unknown1_func0_relay (0x8e0e8c0, 0x86430c0)
trace:nvcuda:wine_cuModuleGetFunction (0x8e0e8b0, 0xf160ffe0, _Z17KernelFluidForceD17PxgFixedSizeArrayI12PxcVectorPadE13ForceDebugGPUPiS_IK6float4ES6_S_IKfES_IKjESA_SA_SA_)
...
```

**Comment by DarkPlayer** [comment]
Can you post a log with `WINEDEBUG=+nvapi` for both cases? (new and old PhysX versions)

**Comment by felixonmars** [comment]
Shipped PhysX: https://paste.xinu.at/STwH/
System PhysX: https://paste.xinu.at/uYGg3/

**Comment by titan73** [comment]
Any news on that issue?
Second argument of wine_cuDeviceGetAttribute looks wrong or maybe it should be another function:
trace:nvcuda:wine_cuDeviceGetAttribute (0x267f218, 537396226, 0)

**Comment by titan73** [comment]
btw pastbin logs are no more accessible

**Comment by titan73** [comment]
Forget comment wine_cuDeviceGetAttribute.

**Comment by DarkPlayer** [comment]
@titan73 I am not sure if the problem is related to nvcuda or maybe our nvapi stubs. It will most probably be necessary to attach a debugger to find out which return value the games does not like. I just don't know whether it makes sense to buy the game if you can workaround the issue simply by replacing the dlls with a more recent version.

**Comment by slackner** [comment]
Hi everyone,

About one year ago, we announced that we would like to move to more advanced bug tracker. We are sorry for the inconvenience, but now its time to say finally goodbye to the old one. This means, all remaining opened bugs (including this one!) will be closed, and no longer available. If you still need any information from the old bugtracker, please write a mail to webmaster@fds-team.de.

More important, if your issue still exists, please open a new bug report at one of the places mentioned below. For bug reports, please attach terminal output from a recent Wine version (preferably >= 1.8). Please note that in the meantime, Wine Staging has become an official part of WineHQ, so if your issue is already tracked at winehq.org, there is NO NEED to open a new bug report for it. Feel free to add the Wine Staging maintainers (sebastian@fds-team.de, michael@fds-team.de) as CC if you want us to take a look at your bug report.

**NEW BUG TRACKERS:**

* For all Wine AND Wine Staging bugs. USE THIS IF IN DOUBT. (*)
  https://bugs.winehq.org/enter_bug.cgi?product=Wine

* For packaging issues:
  https://bugs.winehq.org/enter_bug.cgi?product=Packaging

* For patch submission:
  https://bugs.wine-staging.com/enter_bug.cgi

Best regards,
Sebastian

----

(*) The "Wine Staging" product in the winehq bugtracker should only be used, when your problem turns out to be a regression introduced in "Wine Staging". Since most problems also occur with Wine, it is recommended to open your bug in the "Wine" product, unless someone can show that it doesn't occur with the development branch.
